theme: jekyll-theme-slate
title: Mila Computer Calculus RG
description: Reading about differential, integral and logical calculi.<script type="text/javascript" id="MathJax-script" async   src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"> </script> <script>   MathJax = {     tex: {       inlineMath: [['$', '$']]     }   }; </script>
